# Generated by Django 3.1.1 on 2020-09-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('types', models.CharField(choices=[('ACC', 'AC'), ('NOR', 'NORMAL'), ('QUE', 'QUEEN'), ('KIG', 'KING'), ('XYX', 'COUPLE-FRIENDLY'), ('NAC', 'NON-AC')], max_length=3)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
