# Generated by Django 3.1.1 on 2020-09-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyo', '0002_auto_20200912_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='idcard',
            field=models.CharField(choices=[('DLI', 'DRIVING-LICENCE'), ('AAD', 'AADHAR'), ('PAS', 'PASSPORT')], default='none', max_length=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='meals',
            field=models.CharField(choices=[('BKFST', 'BREAKFAST'), ('NA', 'NOTHING'), ('LUC', 'LUNCH'), ('DIN', 'DINNER')], default='none', max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='types',
            field=models.CharField(choices=[('XYX', 'COUPLE-FRIENDLY'), ('ACC', 'AC'), ('NOR', 'NORMAL'), ('QUE', 'QUEEN'), ('NAC', 'NON-AC'), ('KIG', 'KING')], max_length=3),
        ),
    ]
