# Generated by Django 3.1.1 on 2020-09-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyo', '0003_auto_20200912_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='idcard',
            field=models.CharField(choices=[('PAS', 'PASSPORT'), ('AAD', 'AADHAR'), ('DLI', 'DRIVING-LICENCE')], default='none', max_length=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='meals',
            field=models.CharField(choices=[('BKFST', 'BREAKFAST'), ('LUC', 'LUNCH'), ('NA', 'NOTHING'), ('DIN', 'DINNER')], default='none', max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='types',
            field=models.CharField(choices=[('KIG', 'KING'), ('NAC', 'NON-AC'), ('QUE', 'QUEEN'), ('ACC', 'AC'), ('XYX', 'COUPLE-FRIENDLY'), ('NOR', 'NORMAL')], max_length=3),
        ),
    ]
