# Generated by Django 3.1.1 on 2020-09-12 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yoyo', '0004_auto_20200912_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='idcard',
            field=models.CharField(choices=[('PAS', 'PASSPORT'), ('DLI', 'DRIVING-LICENCE'), ('AAD', 'AADHAR')], default='none', max_length=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='meals',
            field=models.CharField(choices=[('DIN', 'DINNER'), ('BKFST', 'BREAKFAST'), ('NA', 'NOTHING'), ('LUC', 'LUNCH')], default='none', max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='types',
            field=models.CharField(choices=[('NAC', 'NON-AC'), ('NOR', 'NORMAL'), ('KIG', 'KING'), ('XYX', 'COUPLE-FRIENDLY'), ('QUE', 'QUEEN'), ('ACC', 'AC')], max_length=3),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoyo.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
