# Generated by Django 3.1.1 on 2020-09-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoyo', '0006_auto_20200912_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='idcard',
            field=models.CharField(choices=[('PAS', 'PASSPORT'), ('AAD', 'AADHAR'), ('DLI', 'DRIVING-LICENCE')], default='none', max_length=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='meals',
            field=models.CharField(choices=[('DIN', 'DINNER'), ('BKFST', 'BREAKFAST'), ('NA', 'NOTHING'), ('LUC', 'LUNCH')], default='none', max_length=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='types',
            field=models.CharField(choices=[('KIG', 'KING'), ('QUE', 'QUEEN'), ('XYX', 'COUPLE-FRIENDLY'), ('ACC', 'AC'), ('NOR', 'NORMAL'), ('NAC', 'NON-AC')], max_length=3),
        ),
    ]
